### PR TITLE
Fixed compiling error with new MOOSE #25

### LINKED ISSUE #25: Investigate test failure with new MOOSE
As outlined in idaholab/moose#24499 the `THM_doublet` test is failing with new MOOSE.

### PR DESCRIPTION
**Pull request by ajacquey**
These changes fix a bug with the new MOOSE installation.

The file in question is `GolemKernelTimeT.C`

### CODE REVIEW

File: src/kernels/GolemKernelTimeT.C [hunk 1]
```diff
@@ -304,7 +309,7 @@ GolemKernelTimeT::computeOffDiagJacobian(const unsigned int jvar_num)
             if ((_has_disp && _has_pf) && (jvar_num == _disp_var[i]))
               jac += _dT_kernel_time_dev[_qp] * dT_dt * _grad_phi[_j][_qp](i);
 
-          ke(_i, _j) += _scaling_factor[_qp] * weight * jac;
+          _local_ke(_i, _j) += _scaling_factor[_qp] * weight * jac;
         }
   }
 }
```
Comment (lindsayad) [inline src/kernels/GolemKernelTimeT.C:333]: You just need to add `accumulateTaggedLocalMatrix()` right before this line

**Review by lindsayad — APPROVED** [review]

**Comment by ajacquey** [comment]
Thanks @lindsayad
